when:
  - event: push
    branch: master

steps:
  - name: build-frontend
    image: node:20-alpine
    environment:
      CI: "true"
    commands:
      - npm ci
      - npm run build
      - echo "Frontend build completed"

  - name: deploy-to-production
    image: alpine:latest
    environment:
      DEPLOY_HOST:
        from_secret: deploy_host
      DEPLOY_USER:
        from_secret: deploy_user
      DEPLOY_SSH_KEY:
        from_secret: deploy_ssh_key
      DEPLOY_PATH:
        from_secret: deploy_path
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
      - |
        ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "
          cd $DEPLOY_PATH &&
          docker compose -f docker-compose.prod.yml down 2>/dev/null || true &&
          rm -rf public/build &&
          mkdir -p public/build
        "
      - rsync -avz --delete --exclude='.git' --exclude='node_modules' --exclude='storage/logs/*' --exclude='storage/framework/sessions/*' --exclude='storage/framework/cache/*' --exclude='.env' ./ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"
      - |
        ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "
          cd $DEPLOY_PATH &&
          chmod +x deploy.sh &&
          ./deploy.sh
        "
