when:
  - event: push
    branch: master

steps:
  - name: build-frontend
    image: node:20-alpine
    environment:
      CI: "true"
    commands:
      - npm ci
      - npm run build
      - echo "Frontend build completed"

  - name: deploy-to-production
    image: docker:latest
    environment:
      DEPLOY_HOST:
        from_secret: deploy_host
      DEPLOY_USER:
        from_secret: deploy_user
      DEPLOY_SSH_KEY:
        from_secret: deploy_ssh_key
      DEPLOY_PATH:
        from_secret: deploy_path
    commands:
      # Setup SSH
      - apk add --no-cache openssh-client rsync git
      - mkdir -p ~/.ssh
      - echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
      
      # Deploy code to server
      - echo "Deploying to $DEPLOY_HOST:$DEPLOY_PATH"
      # Stop containers to release file locks and allow permission changes
      - echo "Stopping containers to release file locks..."
      - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && docker compose -f docker-compose.prod.yml down 2>/dev/null || true"
      # Remove public/build directory on server to avoid permission issues
      # This ensures rsync can create it fresh with correct permissions
      - echo "Cleaning up public/build directory..."
      - ssh $DEPLOY_USER@$DEPLOY_HOST "rm -rf $DEPLOY_PATH/public/build 2>/dev/null || true"
      # Sync files with rsync
      - echo "Syncing files to server..."
      - rsync -avz --delete --exclude='.git' --exclude='node_modules' --exclude='storage/logs/*' --exclude='storage/framework/sessions/*' --exclude='storage/framework/cache/*' --exclude='.env' ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
      
      # Verify docker directory was synced
      - echo "Verifying deployment files..."
      - ssh $DEPLOY_USER@$DEPLOY_HOST "ls -la $DEPLOY_PATH/docker/entrypoint.sh"
      
      # Run deployment commands on server (this will rebuild and start containers)
      - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && ./deploy.sh"
      
      - echo "Deployment completed successfully!"